library(ggcor)
library(dplyr)
library(ggplot2) 
head(corr)
head(mantel)
quickcor(corr)+geom_color()
quickcor(corr,cor.test = T,type = "lower")+geom_square(data = get_data(type = "lower", show.diag = F))
quickcor(corr,cor.test = T,type = "lower")+  geom_square(data = get_data(type = "lower", show.diag = F))+scale_fill_gradientn(colours = rev(c( "#DAA520","#90EE90", "#00008B")), breaks = seq(-1, 1, 0.5), limits=c(-1,1))+geom_mark(data = get_data(type = "lower",show.diag = F),r = NA,sig.thres = 0.05,size = 5)
mantel <- mantel_test(mantel, corr, spec.select = list(YPP = 1, TAsA=2))
mantel <- mantel%>% mutate(r_cofficient = cut(r, breaks = c(-Inf, 0.2, 0.4, Inf), labels = c("< 0.2", "0.2 - 0.4", ">= 0.4")), p_value = cut(p.value, breaks = c(-Inf, 0.01, 0.05, Inf), labels = c("< 0.01", "0.01 - 0.05", ">= 0.05")))
quickcor(corr, cor.test = T,type = "upper") +  geom_square() +  scale_fill_gradientn(colours = rev(c( "#ffa83a","#dc4fff", "#cacdd2")), breaks = seq(-1, 1, 0.5), limits = c(-1, 1)) + geom_mark(data = get_data(type = "upper",show.diag = F),r = NA,sig.thres = 0.05,size = 5) + anno_link(aes(colour = p_value, size = r_cofficient), data = mantel) +  scale_size_manual(values = c(0.5, 1, 2)) + scale_colour_manual(values = c("#D95F02", "#1B9E77", "#A2A2A288")) + guides(size = guide_legend(title = "Mantel's r", override.aes = list(colour = "grey35"), order = 2), colour = guide_legend(title = "Mantel's p", override.aes = list(size = 3), order = 1),  fill = guide_colorbar(title = "Pearson's r", order = 3))
tiff("PHYSIOLOGY MANTEL.tiff", width = 6, height = 6, units = "in", res = 600)
quickcor(corr, cor.test = T,type = "upper") +  geom_square() +  scale_fill_gradientn(colours = rev(c( "#ffa83a","#dc4fff", "#cacdd2")), breaks = seq(-1, 1, 0.5), limits = c(-1, 1)) + geom_mark(data = get_data(type = "upper",show.diag = F),r = NA,sig.thres = 0.05,size = 5) + anno_link(aes(colour = p_value, size = r_cofficient), data = mantel) +  scale_size_manual(values = c(0.5, 1, 2)) + scale_colour_manual(values = c("#D95F02", "#1B9E77", "#A2A2A288")) + guides(size = guide_legend(title = "Mantel's r", override.aes = list(colour = "grey35"), order = 2), colour = guide_legend(title = "Mantel's p", override.aes = list(size = 3), order = 1),  fill = guide_colorbar(title = "Pearson's r", order = 3))
dev.off()
